### ISSUE TITLE
text clarification in Section 1.2.2

### ISSUE THREAD

**Issue by mglt** [ietf-wg-drip/draft-ietf-drip-arch#10]
1.2.2.  Network RID
"""
   at either end with the Internet between.  For all, but the simplest
   hobby aircraft, telemetry (at least position and heading) flows from
   the UA to the GCS via some path, typically the reverse of the C2
   path.  Thus, RID information pertaining to both the GCS and the UA
   can be sent, by whichever has Internet connectivity, to the Net-RID
   SP, typically the USS managing the UAS operation.
"""

I am reading the text as mentioning that the simplest hobby aircraft are excluded from the discussion. I think the reason is that they do not have telemetry flows. If that is the case, I suggest that one either mention the two categories of aircraft explicitly, or remove the distinction. More specifically - assuming my interpretation is correct - it seems evident that the text precludes the existence of such flow, while the current text - at least my reading of it - let suppose there might be another (simpler) path.

**Comment by ShuaiZhao** [comment]
@mglt  I actually agree there is no need to be very specific about what hobby aircraft may/not be in the picture. 

i propose to remove the "For all, but the simplest hobby aircraft"

**Comment by mglt** [comment]
I agree.

**Comment by cardsw** [comment]
It should not be assumed that all UAS have a flow of telemetry from the UA to the GCS. Some simple hobby aircraft don't. If the link is not there to support telemetry, it cannot be re-used to support Network RID.

**Comment by ShuaiZhao** [comment]
For all but the simplest hobby aircraft, telemetry (at least position and heading) flows from the UA to the GCS via some path, typically the reverse of the C2 path. Thus, RID information pertaining to both the GCS and the UA can be sent, by whichever has Internet connectivity, to the Net-RID SP, typically the USS managing the UAS operation.

`> Editor-note 3:  Does all UAS support telemetry? explain what are simplsest hobby aircraft vs UAS in general. Is it necessay to keep "For all but the simplest hobby aircraft"?`

**Comment by mglt** [comment]
i propose to remove the "For all, but the simplest hobby aircraft". If not it should be clearly justified so the reader understands why we are making such distinction.

**Comment by ShuaiZhao** [comment]
implemented as following: 

`Telemetry (at least UA's position and heading) flows from the UA to the GCS via some path, typically the reverse of the C2 path. Thus, RID information pertaining to both the GCS and the UA can be sent, by whichever has Internet connectivity, to the Net-RID SP, typically the USS managing the UAS operation.
`
