### ISSUE TITLE
potential text clarification

### ISSUE THREAD

**Issue by mglt** [ietf-wg-drip/draft-ietf-drip-arch#11]
1.2.2.  Network RID
"""
[F3411-19] prescribes the protocols only between the Net-RID SP, Net-
RID DP, and the Discovery and Synchronization Service (DSS).  DRIP
may also address standardization of protocols between the UA and GCS,
between the UAS and the Net-RID SP, and/or between the Net-RID DP and
Observer devices.
"""

Just to makes sure I understand correctly, prescribes means they specify the protocols, as opposed to expect the IETF to define these protocols. 
I think that the confusion may partly comes from the text mentioning that DRIP may "also".

**Comment by ShuaiZhao** [comment]
> Just to makes sure I understand correctly, prescribes means they specify the protocols, as opposed to expect the IETF to define these protocols.

@mglt   My reading from the F3411-19 is that those elements need some protocol to support communication. FAA may use IETF existing protocols to address those issues. 

> I think that the confusion may partly comes from the text mentioning that DRIP may "also".

@boucadair should we say " DRIP can address standardization of protocols.."??

**Comment by mglt** [comment]
My impression is that it might be better to say DRIP does xxxx. In the future DRIP may do yyy. The latter being informative.

**Comment by cardsw** [comment]
Neither ASTM nor FAA is leaving it specifically to IETF to define those protocols, but leaving them open to UAS manufacturers and USS operators to do whatever they like. Bob would like DRIP to standardize some of those protocols. Our doing so would add value but is not essential to the mission of DRIP, thus "also".

**Comment by ShuaiZhao** [comment]
{{F3411-19}} prescribes the protocols only between the Net-RID SP, Net-RID DP, and the Discovery and Synchronization Service (DSS). DRIP may also address standardization of protocols between the UA and GCS, between the UAS and the Net-RID SP, and/or between the Net-RID DP and Observer devices.

`> Editor-note 4:  "DRIP may also..." Specify what protocol DRIP can or will standardize. `

**Comment by mglt** [comment]
A clear distinction should be made between what needs to be standardize and what MAY be standardize. The need part should consider the minimal mandatory protocols for interoperability . Other will be nice to have with less than 200% chance of being proceeded in the WG.

**Comment by ShuaiZhao** [comment]
implemented as following: 

`{{F3411-19}} prescribes the protocols between the Net-RID SP, Net-RID DP, and the Discovery and Synchronization Service (DSS).  It also prescribes data elements (in JSON) between Observer and DSS. DRIP addresses standardization of secure protocols between the UA and GCS (over direct wireless and Internet connection), between the UAS and the Net-RID SP, and/or between the Net-RID DP and Observer devices.
`
