### ISSUE TITLE
text clarification in Section 1.3

### ISSUE THREAD

**Issue by mglt** [ietf-wg-drip/draft-ietf-drip-arch#12]
1.3.  Overview of USS Interoperability
"""
about observed UA to a USS.  USS exchange information via a Discovery
and Synchronization Service (DSS) so all USS collectively have
knowledge about all activities in a 4D airspace.
"""

I am wondering if this is all USSes or USSs or USS. If there is anything to change, please apply the change to the full document.

**Comment by ShuaiZhao** [comment]
> I am wondering if this is all USSes or USSs or USS. If there is anything to change, please apply the change to the full document.

@mglt  F3411-19 uses "**USSs**" when there are more than one USS. I will do the update in the next revision. 

Consider this is closed.
