### ISSUE TITLE
clarification in Section 1.4

### ISSUE THREAD

**Issue by mglt** [ietf-wg-drip/draft-ietf-drip-arch#13]
1.4.  Overview of DRIP Architecture

"""
This document outlines the UAS RID architecture into which DRIP must
fit and the architecture for DRIP itself.  This includes presenting

"""
It is not entirely clear to me what "DRIP must fit" means. I am inclined to say that "into which DRIP must fit and the architecture for DRIP itself" can be removed.

**Comment by ShuaiZhao** [comment]
> It is not entirely clear to me what "DRIP must fit" means. I am inclined to say that "into which DRIP must fit and the architecture for DRIP itself" can be removed.

@mglt   seems fine to me, will reflect in -14. Consider this is closed.
