### ISSUE TITLE
clarification section 4

### ISSUE THREAD

**Issue by mglt** [ietf-wg-drip/draft-ietf-drip-arch#16]
4.  HHIT for DRIP Entity Identifier
"""
   use as the UAS Remote ID.  HHITs self-attest to the included explicit
   hierarchy that provides Registrar discovery for 3rd-party ID
"""

The following sentence is a bit cryptic at least to me. I would recommend to clarify it.

**Comment by ShuaiZhao** [comment]
@mglt   See the following proposed new text:

 ```
A 3rd-party who is looking for ID attestation can use the registrar discovery service provided by HHIT's hierarchical self-attest design. 
```

@ Bob, any suggestions?

**Comment by mglt** [comment]
responding a bit out of context. It is a bit unclear to me what the  registrar discovery service is. If that is the registrar indicated by the HHIT it seems to me clarifying to mention it explicitly. Overall, the mechanisms involved seems to me sufficiently simple so their description could replace an obscure function that requires a deep understanding of the solution - HHIT in our case. The goal of this arch docu seems to me that the reader should take it as a starting point, so it should provide an overview of the solution as well as the various proposals. Then, the reader may need a deeper understanding in which case it will go through the details of a specific document.  

A 3rd-party who is looking for ID attestation retrieves the necessary information to the registrar via a DNS request [HHIT]. 

Eventually, we may complement by describing how the self-attestation is performed.

**Comment by cardsw** [comment]
General: We don't have "various proposals". We have one: HHITs, DNS, EPP, RDAP. We barely have time to affect the world by standardizing that one. The world will literally fly past us (within the next 6 months) if we continue to waffle. Specific: a HHIT contains a numerical identifier of the registry in which it should be found; DNS enables that to be resolved to various other info; the registry ID in the HHIT, along with all the other info embedded in the HHIT, is "self-attested". Not sure what we want to say here.

**Comment by ShuaiZhao** [comment]
implemented at following: 

A HHIT, together with the Host Identity (HI) from which it is partly derived, self-attests to its included explicit registration hierarchy, providing Registrar discovery for **_a 3rd-party who is looking for ID attestation retrieves the necessary information to the registrar via a DNS request {{HHIT}}._**

> Editor-note 6: Is there a need to specify how self-attest works? if yes then where? possisble a new section under {{rid}}}

**Comment by mglt** [comment]
The sentence can be clarified and probably using a more direct style would help.
"HHIT self attests". Since the terminology defines attestation I think we should stick closer to it. Could the Registrar be considered as a claim as well as the HI itself ?
As I understand, the HHIT itself does not make possible the signature verification, so this should be clarified as well in my opinion.

**Comment by ShuaiZhao** [comment]
improved text below:


```
# HHIT as the DRIP Entity Identifier # {#rid}

This section describes the DRIP architectural approach to meeting the basic requirements of a DRIP entity identifier within external technical standard ASTM {{F3411-19}} and regulatory constraints. It justifies and explains the use of Hierarchical Host Identity Tags (HHITs) as self-asserting IPv6 addresses suitable as a UAS ID type and more generally as trustworthy multipurpose remote identifiers.

Self-asserting in this usage is given the Host Identity (HI), the HHIT ORCHID construction and a signature of the HHIT by the HI can both be validated. The explicit registration hierarchy within the HHIT provides registry discovery (managed by a Registrar) to either yield the HI for 3rd-party (who is looking for ID attestation) validation or prove the HHIT and HI have uniquely been registered.
```
