### ISSUE TITLE
nits section 4.2

### ISSUE THREAD

**Issue by mglt** [ietf-wg-drip/draft-ietf-drip-arch#24]
4.2.  HIT as A Trustworthy DRIP Entity Identifier

"""
 HITs are so designed; they are statistically unique through the
"""

Maybe a simpler formulation might be preferred. 

s/HITs are so designed; they are statistically u/HITs are statistically u/

**Comment by ShuaiZhao** [comment]
@mglt i have updated to 
~~~
The HITs is designed statistically unique through the cryptographic hash feature of second-preimage resistance.
~~~

Consider this is closed unless you have a better suggestion.. Thanks,
