### ISSUE TITLE
merge section 2 and 3 (from review of -13)

### ISSUE THREAD

**Issue by ShuaiZhao** [ietf-wg-drip/draft-ietf-drip-arch#29]
From Stu:

Let's merge these, as we did in -reqs, with the current 2 becoming 2.1.

The only abbreviations listed here that are not in the glossary in
-reqs are: EdDSA, HHIT, HIT, HIP, RID (which stand-alone, outside
"UAS RID", should be used with care); should we add these to the
glossary in -reqs and delete them here, or leave well enough alone?

Also, -reqs says
   [RFC4949] provides a glossary of Internet security terms that should
   be used where applicable.

   In the UAS community, the plural form of acronyms generally is the
   same as the singular form, e.g., Unmanned Aircraft System (singular)
   and Unmanned Aircraft Systems (plural) are both represented as UAS.
   On this and other terminological issues, to encourage comprehension
   necessary for adoption of DRIP by the intended user community, that
   community's norms are respected herein, and definitions are quoted in
   cases where they have been found in that community's documents.  Most
   of the listed terms are from that community (even if specific source
   documents are not cited); any that are DRIP-specific or invented by
   the authors of this document are marked "(DRIP)".
Do we want to repeat this, in whole or in part, here in -arch?

**Comment by mglt** [comment]
I understand that the concern is about merging sections of the terminology. 
3.1.  Additional Definitions

   This document uses terms defined in [I-D.ietf-drip-reqs].

3.2.  Abbreviations

   ADS-B:      Automatic Dependent Surveillance Broadcast

   DSS:        Discovery & Synchronization Service

   EdDSA:      Edwards-Curve Digital Signature Algorith
..
 into 


3.1.  Abbreviations

   This document uses terms defined in [I-D.ietf-drip-reqs].

   ADS-B:      Automatic Dependent Surveillance Broadcast

   DSS:        Discovery & Synchronization Service

   EdDSA:      Edwards-Curve Digital Signature Algorith

Which I see as a non issue. I woudl not recommend to define terms in the req document that will be used in arch.

**Comment by cardsw** [comment]
The WG previously agreed, and has repeatedly sustained the decision, 
that DRIP terms would be defined in -reqs, even if not used in -reqs, if 
expected to be used in other DRIP docs.

In accordance with that, -reqs 2.2 states

> This section defines a non-comprehensive set of terms expected to be
> used in DRIP documents.  This list is meant to be the DRIP
> terminology reference; as such, some of the terms listed below are
> not used in this document.

If a term will be used _only_ in -arch, then defining it only in -arch 
makes sense; but if we also expect to use it in other DRIP docs, such as 
Bob's -uas-rid, then we should define it in -reqs.

On 6/28/2021 1:38 PM, mglt wrote:
> I understand that the concern is about merging sections of the terminology.
> ...
> I woudl not recommend to define terms in the 
> req document that will be used in arch.


-- 
Stuart W. Card, PhD: VP & Chief Scientist, Critical Technologies Inc.
* Creativity * Diversity * Expertise * Flexibility * Integrity *
Suite 400 Technology Center, 4th Floor 1001 Broad St, Utica NY 13501
315-793-0248 x141 FAX -9710 ***@***.***> www.critical.com

**Comment by ShuaiZhao** [comment]
3.  Definitions and Abbreviations

```
      Editor-note 13: 1) should we merge Section 2 and Section 3 2) how
      should we list abbr in the Arch?  Previous WG agreeement is that
      all the DRIP terms shall be defined in -reqs, which may or may not
      be used in -reqs itself, but other documents such as Arch-. And
      arch- can list terms when they are used in the arch- only.  So
      which is which ?

```

**Comment by mglt** [comment]
I do not see this as a big issue, and arch should define the terms that are used in arch and not already defined in req. I personally do not see req as a terminology document as - until published last - we will unlikely be convinced we have all necessary terms.

**Comment by ShuaiZhao** [comment]
done in -15

```
2.  Terms and Definitions . . . . . . . . . . . . . . . . . . . .   9
     2.1.  Architecture Terminology  . . . . . . . . . . . . . . . .   9
     2.2.  Abbreviations . . . . . . . . . . . . . . . . . . . . . .   9
     2.3.  Additional Definitions  . . . . . . . . . . . . . . . . .  10
   3.  Claims, Assertions, Attestations, and Certificates  . . . . .  10
```
