### ISSUE TITLE
Cite NPA

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-drip/draft-ietf-drip-arch#36]
Consider adding a pointer to https://www.easa.europa.eu/document-library/notices-of-proposed-amendment/npa-2021-14

**Comment by ghost** [comment]
That document refers to https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32021R0664 which is more concerned with broadcast and network identifiers.

**Comment by ShuaiZhao** [comment]
Updated text: 

European Union Aviation Safety Agency (EASA)

      The EASA published a [Delegated] regulation in 2019 imposing
      requirements on UAS manufacturers and third-country operators,
      including but not limited to UAS RID requirements.  

> The same year,
>       EASA also published an [Implementing] regulation laying down
>       detailed rules and procedures for UAS operations and operating
>       personnel then was updated in 2021 [Implementing_update]. 

> A Notice of Proposed Amendment [NPA] was published in 2021 to
>       provide more information about the development of acceptable means
>       of compliance and guidance material to support the U-space
>       regulation.


added reference:


>    [Implementing_update]
>               European Union Aviation Safety Agency (EASA), "EU
>               COMMISSION IMPLEMENTING REGULATION (EU) 2021/664 of 22
>               April 2021 on a regulatory framework for the U-space",
>               2021, <https://eur-lex.europa.eu/legal-content/EN/
>               TXT/?uri=CELEX%3A32021R0664>.
> 
>  [NPA]      European Union Aviation Safety Agency (EASA), "Notice of
>               Proposed Amendment 2021-14 Development of acceptable means
>               of compliance and guidance material to support the U-space
>               regulation", 2021,
>               <https://www.easa.europa.eu/downloads/134303/en>.
