### ISSUE TITLE
Prefix FAA with US

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-drip/draft-ietf-drip-arch#37]
Please use US FAA through the document.

**Comment by ShuaiZhao** [comment]
Do we need to prefix "US" in all FAA occurrences? Maybe just at the beginning of this doc when section 1.1 first introduces FAA? 


>    Federal Aviation Administration (FAA)
> 
>       The FAA published a Notice of Proposed Rule Making [NPRM] in 2019
>       and thereafter published a "Final Rule" in 2021 [FAA_RID],
>       imposing requirements on UAS manufacturers and operators, both
>       commercial and recreational.  The rule clearly states that
>       Automatic Dependent Surveillance Broadcast (ADS-B) Out and
>       transponders cannot be used to satisfy the UAS RID requirements on
>       UAS to which the rule applies (see Appendix B).

to
US Federal Aviation Administration (FAA)

**Comment by boucadair** [comment]
Works for me unless @evyncke has a preference.

**Comment by evyncke** [comment]
This works for me as well

**Comment by ShuaiZhao** [comment]
Agreed on adding Prefix "USA" in section 1.1 only.
