### ISSUE TITLE
IoT Directorate Review

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-drip/draft-ietf-drip-arch#38]
From Thomas Fossati:

```
* In some IETF circles (e.g., RATS & TEEP) "attestation" has a precise
  meaning, which is quite distinct from the DRIP definition "[…]
  normally used when an entity asserts a relationship with another
  entity".  Specifically, unless the signing key is derived from the
  measured boot state (a la DICE), or the claims are of a certain kind,
  the process that this doc names "attestation" is not what is meant
  usually.
   => Maybe add a few words to Section 2.2 to clarify the distinction
      between DRIP attestation and RATS's, e.g., by adding a disclaimer
      similar to that already associated with DRIP certs.

* Apropos "remote attestation", I am wondering whether, given the type
  of endpoints considered in the architecture - and in particular
  provided their increased exposure to physical compromise, and the
  potentially large impact on the overall system and beyond - the
  architecture should provide explicit channels for securely conveying
  the verification of the installed and booted firmware (as well as any
  other relevant trust metrics)?

* I haven't read the rest of the DRIP docs, so I am not sure why is
  EdDSA specifically mentioned in Section 3.2.?  Is this a requirement
  or just an example?  I guess the latter, but checking just in case.
  And apropos that, in light of fault attacks on deterministic ECDSA and
  EdDSA [0] that are potentially easier to carry out against UAs (BTW,
  how cool is a fault attack w/ private key exfiltration carried out by
  a chasing drone?) maybe it's worth adding to the security
  considerations some words around physical attacks and their impact
  on the choice of signature algorithms?

* It'd seem that, given the very low bandwidth, DoS (as well as Denial
  of View) attacks on communication involving the UA should be quite
  easy to mount?  Maybe worth spending some words on the argument
  to describe what the threats are and which mitigations are available.

* This is a question more than anything else: given the constrained
  nature of UAs, I was wondering whether it is envisaged that the
  end-to-end network path will be realised with the use of more capable
  (trusted) proxy nodes?  If so, there may be a few security and privacy
  considerations to be added.

# Nits

* AAA is usually intended as "Authentication, Authorization, and
  Accounting" (see also [1]), whereas here it's got four new A's:
  Attestation, Access Control , Attribution, Audit :-)
    => Maybe change it to 7A, A7, AAA+ or similar? 

* In Section 2.1, the following terms are already in the most recent
  "RFC Editor Abbreviations List" [1] and can be removed:
    * EdDSA
    * HIP
    * HIT
    * HI

* Some typographic inconsistency around Bluetooth: Is it 4 or 4.x?
  5 or 5.x?
    => Stick to one format. (Also maybe add an explicit reference to the
       Bluetooth specs.)

[0] https://eprint.iacr.org/2020/803
[1] https://www.rfc-editor.org/materials/abbrev.expansion.txt
```

**Comment by ShuaiZhao** [comment]
> # Nits
> 
> * AAA is usually intended as "Authentication, Authorization, and
>   Accounting" (see also [1]), whereas here it's got four new A's:
>   Attestation, Access Control , Attribution, Audit :-)
>     => Maybe change it to 7A, A7, AAA+ or similar? 
> 
Shuai/ opt with AAA+, any suggestions from authors? 


> * In Section 2.1, the following terms are already in the most recent
>   "RFC Editor Abbreviations List" [1] and can be removed:
>     * EdDSA
>     * HIP
>     * HIT
>     * HI

Shuai/ I would suggest we don't remove that. I recall that were discussions to add those terms in section 2.1 during WGLC

> * Some typographic inconsistency around Bluetooth: Is it 4 or 4.x?
>   5 or 5.x?
>     => Stick to one format. (Also maybe add an explicit reference to the
>        Bluetooth specs.)
> 
> [0] https://eprint.iacr.org/2020/803
> [1] https://www.rfc-editor.org/materials/abbrev.expansion.txt

Shuai/ @cardsw, which Bluetooth version do we opt to? And is that necessary to add reference?

**Comment by boucadair** [comment]
> > * AAA is usually intended as "Authentication, Authorization, and
> >   Accounting" (see also [1]), whereas here it's got four new A's:
> >   Attestation, Access Control , Attribution, Audit :-)
> >   => Maybe change it to 7A, A7, AAA+ or similar?
> 
> Shuai/ opt with AAA+, any suggestions from authors?

I suggest we leave AAA to be consistent with RFC9153.

**Comment by boucadair** [comment]
> > * In Section 2.1, the following terms are already in the most recent
> >   "RFC Editor Abbreviations List" [1] and can be removed:
> >   
> >   * EdDSA
> >   * HIP
> >   * HIT
> >   * HI
> 
> Shuai/ I would suggest we don't remove that. I recall that were discussions to add those terms in section 2.1 during WGLC

Agree

**Comment by ShuaiZhao** [comment]
@cardsw Would you please give suggestions on the following issue? 

> Some typographic inconsistency around Bluetooth: Is it 4 or 4.x?
> 5 or 5.x?
> => Stick to one format. (Also maybe add an explicit reference to the
> Bluetooth specs.)
> [0] https://eprint.iacr.org/2020/803
> [1] https://www.rfc-editor.org/materials/abbrev.expansion.txt
> Shuai/ @cardsw, which Bluetooth version do we opt to? And is that necessary to add reference?

**Comment by rgmhtt** [comment]
WRT to use of EdDSA:  Only EdDSA provides 32 byte public keys.  This is essential in the Authentication Messages defined in draft-ietf-drip-auth.  With ECDSA, you have to use public key compression to get 32 byte keys which then poises the issue with patents.

Thus EdDSA is the 1st defined PK algorithm.  There may be more down the road of deployment.  Experience will drive this.

Also at some future point a PQC solution may be developed that will work within this environment and will then be added.

**Comment by rgmhtt** [comment]
"This is a question more than anything else: given the constrained
  nature of UAs, I was wondering whether it is envisaged that the
  end-to-end network path will be realised with the use of more capable
  (trusted) proxy nodes?  If so, there may be a few security and privacy
  considerations to be added."

This only comes into play with Network Remote ID and Command and Control.  The first draft for this is still a little drafty (draft-moskowitz-secure-nrid-c2) so the architecture doc is thin on this discussion.  Much of it will be what wireless tech will be used.

Proxying NRID is only applicable for UA in LOS operation.  BLOS will require the a WAN wireless.  If LoRaWAN works (might be too much traffic for it, TBD), then there will naturally be a LoRaWAN proxy.

But we are only started down the NRID path for a non-proprietary solution.

**Comment by rgmhtt** [comment]
"It'd seem that, given the very low bandwidth, DoS (as well as Denial
  of View) attacks on communication involving the UA should be quite
  easy to mount?  Maybe worth spending some words on the argument
  to describe what the threats are and which mitigations are available."

The USA FAA and other CAAs have mandated Broadcast RID over Bluetooth and WiFi.  Any DOS attacks against these RF are basically out of scope.  It will happen and the ground observer will not get the messages.

So we have left DOS over RF as nothing worth saying about it.

I will say that this is sometimes brought up as an argument FOR autonomous operations.  You don't want to be forced to land your UA just because of a RF DOS attack; you have a delivery to make.

**Comment by rgmhtt** [comment]
"Shuai/ @cardsw, which Bluetooth version do we opt to? And is that necessary to add reference?"

@kc2rxo needs to jump in here, but I believe that ASTM says to send both BT4 and BT5 from the UA.  Not one or the other.

**Comment by rgmhtt** [comment]
Another point on DOS question.

We did not put DOS discussion into the architecture by intent.  With RF it just is there.  But in the solution documents we specifically deal with it.  Particularly in draft-ietf-drip-auth where the Introduction uses the term "volatile environment" to be more inclusive than just looking a DOS.  We added a FEC solution for BT4 as unlike BT5 and WiFi, it does not have Error Correction built into the PHY.

So just looking at DOS would miss other issues about RF which are best discussed in the solutions.

**Comment by kc2rxo** [comment]
Jumping in as asked on the Bluetooth versioning.

ASTM defines that when doing Bluetooth you MUST be doing both Bluetooth 4 and Bluetooth 5.

I got into the habit of writing it like "Bluetooth 4.x" and "Bluetooth 5.x" to signal that any current or new version of Bluetooth in those areas would be acceptable. For example Bluetooth 5.1 already exists (though I don't know the differences between it and 5.0). If this is not a good practice it would probably be fine to truncate to "Bluetooth 4" and "Bluetooth 5" respectively.

**Comment by thomas-fossati** [comment]
> With ECDSA, you have to use public key compression to get 32 byte keys which then poises the issue with patents.

Just noting that the [HP patent](https://patents.google.com/patent/US6252960) on point compression expired 4 years ago.  Are you referring to something else?

**Comment by thomas-fossati** [comment]
> Thus EdDSA is the 1st defined PK algorithm. There may be more down the road of deployment. Experience will drive this.
> 
> Also at some future point a PQC solution may be developed that will work within this environment and will then be added.

Agree.  I guess what I was after is to state the size requirement more clearly and to give EdDSA as an example that satisfies the requirement.

**Comment by thomas-fossati** [comment]
> Another point on DOS question.
> 
> We did not put DOS discussion into the architecture by intent. With RF it just is there. But in the solution documents we specifically deal with it. Particularly in draft-ietf-drip-auth where the Introduction uses the term "volatile environment" to be more inclusive than just looking a DOS. We added a FEC solution for BT4 as unlike BT5 and WiFi, it does not have Error Correction built into the PHY.
> 
> So just looking at DOS would miss other issues about RF which are best discussed in the solutions.

This is excellent.  I suggest adding it to the document to provide a (great) rationale for de-scoping.

**Comment by rgmhtt** [comment]
On 5/12/22 07:08, Thomas Fossati wrote:
>
>     With ECDSA, you have to use public key compression to get 32 byte
>     keys which then poises the issue with patents.
>
> Just noting that the HP patent 
> <https://patents.google.com/patent/US6252960> on point compression 
> expired 4 years ago. Are you referring to something else?
>

The Certicom patents?

And I did loose track of the patent dates.  Someone else pointed this 
out to me. But I began this process 4 years ago when I selected EdDSA.

**Comment by rgmhtt** [comment]
On 5/12/22 07:11, Thomas Fossati wrote:
>
>     Thus EdDSA is the 1st defined PK algorithm. There may be more down
>     the road of deployment. Experience will drive this.
>
>     Also at some future point a PQC solution may be developed that
>     will work within this environment and will then be added.
>
> Agree. I guess what I was after is to state the size requirement more 
> clearly and to give EdDSA as an example that satisfies the requirement.
>

I am also following closely the NIST Lightweight Crypto work, and this 
may well give an alternative to cSHAKE128.  It would be nice, if NIST 
used the LWC hash in FIPS 186-5 which has been in draft status for 
years.  Then we could probably eliminate SHA2 code from many devices...

**Comment by thomas-fossati** [comment]
> The Certicom patents?

To my knowledge they have all expired -- more or less recently.

(For a list of known filings and the associated expiry dates see also [this](https://en.wikipedia.org/wiki/ECC_patents#Known_patents).)

**Comment by thomas-fossati** [comment]
> I am also following closely the NIST Lightweight Crypto work,

Me too :-) and, as you, I also am hopeful that some good alternative can come out of that.

**Comment by rgmhtt** [comment]
On 5/12/22 08:37, Thomas Fossati wrote:
>
>     I am also following closely the NIST Lightweight Crypto work,
>
> Me too :-) and, as you, I also am hopeful that some good alternative 
> can come out of that.
>

See draft-moskowitz-hip-new-crypto where I 'jumped the gun' with 
Xoodyak.  I worked closely with Team Keccak to get the Cyclist calls 
right.  It is implemented in OpenHIP by Dr. Gurtov's students.

Had some interesting sidebar chats during the LWC workshop this week.  
Simple use of Cyclist addresses attacks that some finalists claim they 
are the only ones solving the attacks (e.g. nonce misuse).

I sent in a negative comment on 186-5 in that SHA2 was used rather than 
cSHAKE128 for EdDSA25519.  I understand that rfc8032 did this for timing 
reasons:  SHA3 was not ready for cSHAKE128 implementations, though it 
was for Ed488.  Go figure.

So I am rooting for Xoodyak to make it to the finish line and I am well 
along.

**Comment by ShuaiZhao** [comment]
summary: 

> * In some IETF circles (e.g., RATS & TEEP) "attestation" has a precise
>   meaning, which is quite distinct from the DRIP definition "[…]
>   normally used when an entity asserts a relationship with another
>   entity".  Specifically, unless the signing key is derived from the
>   measured boot state (a la DICE), or the claims are of a certain kind,
>   the process that this doc names "attestation" is not what is meant
>   usually.
>    => Maybe add a few words to Section 2.2 to clarify the distinction
>       between DRIP attestation and RATS's, e.g., by adding a disclaimer
>       similar to that already associated with DRIP certs.

Shuai/ Current text is clear enough. agreed on nothing to be updated. 

> * Apropos "remote attestation", I am wondering whether, given the type
>   of endpoints considered in the architecture - and in particular
>   provided their increased exposure to physical compromise, and the
>   potentially large impact on the overall system and beyond - the
>   architecture should provide explicit channels for securely conveying
>   the verification of the installed and booted firmware (as well as any
>   other relevant trust metrics)?

Shuai/ out of scope. agreed on nothing to be updated. 

> * I haven't read the rest of the DRIP docs, so I am not sure why is
>   EdDSA specifically mentioned in Section 3.2.?  Is this a requirement
>   or just an example?  I guess the latter, but checking just in case.
>   And apropos that, in light of fault attacks on deterministic ECDSA and
>   EdDSA [0] that are potentially easier to carry out against UAs (BTW,
>   how cool is a fault attack w/ private key exfiltration carried out by
>   a chasing drone?) maybe it's worth adding to the security
>   considerations some words around physical attacks and their impact
>   on the choice of signature algorithms?
> 

Shuai/ Bob proposed the following text under section 3.2

**Ed25519 {{RFC8032}} is used as the HHIT signing algorithm as {{RFC9153}} GEN-1 and ID-5 can best be met by restricting the HI to 32 bytes. A larger public key would rule out the offline attestation feature that fits within the 200-byte Authentication Message maximum length. Other algorithms that meet this 32 byte constraint can be added as deemed needed.**


> * It'd seem that, given the very low bandwidth, DoS (as well as Denial
>   of View) attacks on communication involving the UA should be quite
>   easy to mount?  Maybe worth spending some words on the argument
>   to describe what the threats are and which mitigations are available.
> 

Shuai/ Bob proposed new text for new subsection 8.3

**8.3 Denial Of Service (DOS) protection out of scope

Remote ID services from the UA use a wireless link in a public space.  As such they are open to many forms of RF jamming.  It is trivial for an attacker to stop any UA's messages reaching a wireless receiver.  Thus it is pointless to attempt to provide relief from DOS attacks as there is always the ultimate RF jamming attack.  Subtle DOS attacks of message content altering are not practical with the basic message Error Correction provided.  Finally this whole architecture is put forth to make DOS spoofing/replay attacks very hard.**

> * This is a question more than anything else: given the constrained
>   nature of UAs, I was wondering whether it is envisaged that the
>   end-to-end network path will be realised with the use of more capable
>   (trusted) proxy nodes?  If so, there may be a few security and privacy
>   considerations to be added.

Shuai/ agreed on nothing to be updated. 

> # Nits
> 
> * AAA is usually intended as "Authentication, Authorization, and
>   Accounting" (see also [1]), whereas here it's got four new A's:
>   Attestation, Access Control , Attribution, Audit :-)
>     => Maybe change it to 7A, A7, AAA+ or similar? 

Shuai/ agreed to stick with AAA. 

> * In Section 2.1, the following terms are already in the most recent
>   "RFC Editor Abbreviations List" [1] and can be removed:
>     * EdDSA
>     * HIP
>     * HIT
>     * HI

Shuai/ agreed not to remove above

> * Some typographic inconsistency around Bluetooth: Is it 4 or 4.x?
>   5 or 5.x?
>     => Stick to one format. (Also maybe add an explicit reference to the
>        Bluetooth specs.)
> 

Shuai/ first use as 4.x, then 4. 

> [0] https://eprint.iacr.org/2020/803
> [1] https://www.rfc-editor.org/materials/abbrev.expansion.txt
> 

Shuai/ agreed not to add the above references.

**Comment by boucadair** [comment]
> > * In some IETF circles (e.g., RATS & TEEP) "attestation" has a precise
> >   meaning, which is quite distinct from the DRIP definition "[…]
> >   normally used when an entity asserts a relationship with another
> >   entity".  Specifically, unless the signing key is derived from the
> >   measured boot state (a la DICE), or the claims are of a certain kind,
> >   the process that this doc names "attestation" is not what is meant
> >   usually.
> >   => Maybe add a few words to Section 2.2 to clarify the distinction
> >   between DRIP attestation and RATS's, e.g., by adding a disclaimer
> >   similar to that already associated with DRIP certs.
> 
> Shuai/ TBD

I tend to leave the current text as it is. 

The current text is clear enough this is about a DRIP definition, and that the term should be interpreted as defined here.  

```
   Assertions:

      An assertion in DRIP is a set of claims.  This definition is
      borrowed from JWT [RFC7519] and CWT [RFC8392].

   Attestations:

      An attestation **in DRIP** is a signed assertion.  The signer may be
      the claimant or a related party with stake in the assertion(s).
      **Under DRIP** this is normally used when an entity asserts a
      relationship with another entity, along with other information,
      and the asserting entity signs the assertion, thereby making it an
      attestation.
```

I checked RATS arch I-D but I failed to find a formal def there. I found one in draft-ietf-rats-tpm-based-network-device-attest, though:

```
   Attestation: the process of generating, conveying and appraising
   claims, backed by evidence, about device trustworthiness
   characteristics, including supply chain trust, identity, device
   provenance, software configuration, device composition, compliance to
   test suites, functional and assurance evaluations, etc. 
```

**Comment by boucadair** [comment]
> > * Apropos "remote attestation", I am wondering whether, given the type
> >   of endpoints considered in the architecture - and in particular
> >   provided their increased exposure to physical compromise, and the
> >   potentially large impact on the overall system and beyond - the
> >   architecture should provide explicit channels for securely conveying
> >   the verification of the installed and booted firmware (as well as any
> >   other relevant trust metrics)?
> 
> Shuai/ TBD

This is definitely out of the scope of DRIP.

**Comment by ShuaiZhao** [comment]
> > > * Apropos "remote attestation", I am wondering whether, given the type
> > >   of endpoints considered in the architecture - and in particular
> > >   provided their increased exposure to physical compromise, and the
> > >   potentially large impact on the overall system and beyond - the
> > >   architecture should provide explicit channels for securely conveying
> > >   the verification of the installed and booted firmware (as well as any
> > >   other relevant trust metrics)?
> > 
> > 
> > Shuai/ TBD
> 
> This is definitely out of the scope of DRIP.

Thanks for confirmation.

**Comment by ShuaiZhao** [comment]
> > > * In some IETF circles (e.g., RATS & TEEP) "attestation" has a precise
> > >   meaning, which is quite distinct from the DRIP definition "[…]
> > >   normally used when an entity asserts a relationship with another
> > >   entity".  Specifically, unless the signing key is derived from the
> > >   measured boot state (a la DICE), or the claims are of a certain kind,
> > >   the process that this doc names "attestation" is not what is meant
> > >   usually.
> > >   => Maybe add a few words to Section 2.2 to clarify the distinction
> > >   between DRIP attestation and RATS's, e.g., by adding a disclaimer
> > >   similar to that already associated with DRIP certs.
> > 
> > 
> > Shuai/ TBD
> 
> I tend to leave the current text as it is.
> 
> The current text is clear enough this is about a DRIP definition, and that the term should be interpreted as defined here.
> 
> ```
>    Assertions:
> 
>       An assertion in DRIP is a set of claims.  This definition is
>       borrowed from JWT [RFC7519] and CWT [RFC8392].
> 
>    Attestations:
> 
>       An attestation **in DRIP** is a signed assertion.  The signer may be
>       the claimant or a related party with stake in the assertion(s).
>       **Under DRIP** this is normally used when an entity asserts a
>       relationship with another entity, along with other information,
>       and the asserting entity signs the assertion, thereby making it an
>       attestation.
> ```
> 
> I checked RATS arch I-D but I failed to find a formal def there. I found one in draft-ietf-rats-tpm-based-network-device-attest, though:
> 
> ```
>    Attestation: the process of generating, conveying and appraising
>    claims, backed by evidence, about device trustworthiness
>    characteristics, including supply chain trust, identity, device
>    provenance, software configuration, device composition, compliance to
>    test suites, functional and assurance evaluations, etc. 
> ```

agreed. Thanks for confirmation

**Comment by kc2rxo** [comment]
> > > * Apropos "remote attestation", I am wondering whether, given the type
> > >   of endpoints considered in the architecture - and in particular
> > >   provided their increased exposure to physical compromise, and the
> > >   potentially large impact on the overall system and beyond - the
> > >   architecture should provide explicit channels for securely conveying
> > >   the verification of the installed and booted firmware (as well as any
> > >   other relevant trust metrics)?
> > 
> > 
> > Shuai/ TBD
> 
> This is definitely out of the scope of DRIP.

While I believe this is out of scope for DRIP in the current charter I strongly believe this is something we would want to recharter for (I already know of one group that would be strongly interested in such a thing).
