### ISSUE TITLE
genart review (Roni Even)

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-drip/draft-ietf-drip-arch#41]
Reviewer: Roni Even
Review result: Ready

I am the assigned Gen-ART reviewer for this draft. The General Area Review Team (Gen-ART) reviews all IETF documents being processed by the IESG for the IETF Chair.  Please treat these comments just like any other last call comments.

For more information, please see the FAQ at

<https://trac.ietf.org/trac/gen/wiki/GenArtfaq>.

Document: draft-ietf-drip-arch-??
Reviewer: Roni Even
Review Date: 2022-04-05
IETF LC End Date: 2022-04-06
IESG Telechat date: Not scheduled for a telechat

Summary:
The document is ready for publication as an informational RFC

One question: I noticed that the document relates to RFC9153 requirements. I
did not see gen-7 and gen-10 addressed .   Gen-7 QoS: DRIP MUST enable
policy-based specification of performance and reliability parameters.

Major issues:

Minor issues:

Nits/editorial comments:

**Comment by rgmhtt** [comment]
Although Gen-7 and Gen-10 are important, they have not been work on for the current architecture.  They will come in on Network Remote ID that is only now being framed.  It will take some work still for them.  Thus 9153 is a placeholder of sorts and somehow they need to be dealt with.

Thus the current architecture is quiet on them.

**Comment by ShuaiZhao** [comment]
Stu: 
> Thanks for the review! I was asked to respond to your question. I agree 
that GEN-7 and GEN-10 may be conspicuous by their absence from the 
architecture document.

> In the initial context of Broadcast RID, GEN-7 (QoS) is a requirement 
primarily on implementations of UAS RID senders that requires no 
explicit architectural support. For example: CAAs may require a minimum 
rate at which RID information is refreshed; in any sender implementation 
intended for use in multiple jurisdictions (or on multiple classes of 
aircraft) with different rate requirements, this would thus need to be a 
configurable parameter; however it need not be remotely configurable, 
thus there is no need to specify a protocol or language for 
getting/setting the parameter value. As Network RID matures, GEN-7 may 
assume broader significance, but we don't want to embed any guesses as 
to that in the current architectural overview. GEN-10 (multicast) is 
even more Network RID specific, so likewise to be addressed in future 
DRIP documents.

Do you feel that the above information should be reflected explicitly in 
the architecture document?

**Comment by ShuaiZhao** [comment]
Roni: 
> Hi,
Thanks for the clarification. I think it may be good to reflect your response in the document for completeness.
Roni

**Comment by ShuaiZhao** [comment]
Shuai: 
> At this moment, the only draft we have to even remotely address the GEN-7 and GEN-10 is the https://datatracker.ietf.org/doc/draft-moskowitz-drip-crowd-sourced-rid/, which is still not a WG draft yet. 

> I suggest we add the Both GEN-7 and GEN-10 in section 6 where CS-RID is introduced in DRIP -arch

> 6.  Harvesting Broadcast Remote ID messages for UTM Inclusion
>    This approach satisfies the following DRIP requirements defined in [RFC9153]: GEN-5, GEN-7, GEN-10, GEN-11, and REG-1.

**Comment by ShuaiZhao** [comment]
Bob:

> And Shuai,
> 
> We need to add a section to crowd-source on the reqs it meets.  Particularly now that we want workgroup adoption.
> 
> Bob

**Comment by ShuaiZhao** [comment]
Stu: 

> Don't forget that section 6 is about CS-RID, which is an optional further extension of DRIP, just as DRIP itself is an extension of F3411. So we can't satisfy GEN-7 for DRIP as a whole in section 6.
> 
> GEN-10 might apply only to CS-RID, so it can be addressed there.
> 
> In both cases, we need to say a few words about how we satisfy the requirement, not just that the requirement is satisfied.

**Comment by ShuaiZhao** [comment]
Bob proposed new Text in section 6 

original
```
   This approach satisfies the following DRIP requirements defined in
   [RFC9153]: GEN-5, GEN-11, and REG-1.

```
new text
```
   This approach satisfies the following DRIP requirements defined in
   [RFC9153]: GEN-5, GEN-11, and REG-1.  As Broadcase messages are
   inherently multicast, GEN-10 is met for local-link multicast to multiple
   FInders (how multilateration is possible).
```

I don't see how this can satisfy GEN-7.  I think that I MAY be able to include it in nrid...
