### ISSUE TITLE
tsvart review (Kyle Rose)

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-drip/draft-ietf-drip-arch#42]
Reviewer: Kyle Rose
Review result: Ready

This document has been reviewed as part of the transport area review team's ongoing effort to review key IETF documents. These comments were written primarily for the transport area directors, but are copied to the document's authors and WG to allow them to address any issues raised and also to the IETF discussion list for information.

When done at the time of IETF Last Call, the authors should consider this review as part of the last-call comments they receive. Please always CC [tsv-art@ietf.org](mailto:tsv-art@ietf.org) if you reply to or forward this review.

Status: Ready (with TSVART-nonspecific LC comments)

I don't see any novel transport issues in this document: there is precedent for everything being proposed, with explicit references to existing RFCs.

Putting my individual reviewer hat on, however:

> Only sending the DET and a signature on frequently changing data that 
> can be
sanity-checked by the Observer (such as a Location/Vector message) proves that the observed UA possesses the claimed UAS ID.

"Frequently changing" is not the right standard for preventing replay attacks:
"novel" is. The idea is that the sender needs to sign data that has never been signed before and moreover that the receiver knows *a priori* would never have been signed by the key owner before. This is why, for instance, time codes are frequently used in such constructions: because time flows in only one direction, everyone has the ability to agree on what the current time is (even in a scenario in which participants are moving at relativistic speeds, a single reference frame can be chosen arbitrarily as the basis for the shared time scale), and no properly-functioning implementation would sign a future time code.

> For that it MUST be registered (under DRIP Registries) and be actively 
> used
by the party (in most cases the UA).

"Must" should probably be lowercase given that this is an informational document. Moreover, given the document overall takes the approach of making recommendations to others about how they can use IETF protocols in their technology space, and given that the IETF is not the protocol police, such recommendations really should be suggestions ("may be registered using such-and-such a protocol") rather than normative requirements.

**Comment by ShuaiZhao** [comment]
From Eric 


> Kyle,
> 
> First, thank you for your technical review on this document. The more eyes on a document, the better the result.
> 
> Allow me to reply, as the responsible AD for DRIP, about your last point: whether this work should happen at the IETF.
> 
> As an IESG member, my view is that the IETF should welcome new pieces of work related to IP technologies. After two BoF, and a community consensus, the DRIP WG was officially formed (i.e., with the IETF community support). While the DRIP meetings do not attract hundreds of people, there are enough IETF engineers to make progress. So, in my opinion, this work can be done at the IETF (albeit other fora could have hosted it as the work is at the border of other fora -- like ICAO). The charter is also explicitly requesting the re-use of existing protocols as much as possible.
> 
> More specifically on this document (and I will let the WG chairs, the doc shepherd, the authors, and the WG to add more), it is an informational document (so no protocol action included) about architecture. So, it is expected (and even required) that such an architecture I-D does not specify anything.
> 
> Finally, other DRIP I-D, notably the RID one, will specify format and processing, i.e., real standards.
> 
> Thank you anyway for your review and your concern on getting the IETF efficient and lean,
> 
> Regards
> 
> -éric

```

**Comment by ShuaiZhao** [comment]
Kyle Reply

On Wed, Apr 6, 2022 at 12:03 PM Eric Vyncke (evyncke) <[evyncke@cisco.com](mailto:evyncke@cisco.com)> wrote:
First, thank you for your technical review on this document. The more eyes on a document, the better the result.

And thank you for the reply!
 

> Allow me to reply, as the responsible AD for DRIP, about your last point: whether this work should happen at the IETF.

> As an IESG member, my view is that the IETF should welcome new pieces of work related to IP technologies. After two BoF, and a community consensus, the DRIP WG was officially formed (i.e., with the IETF community support). While the DRIP meetings do not attract hundreds of people, there are enough IETF engineers to make progress. So, in my opinion, this work can be done at the IETF (albeit other fora could have hosted it as the work is at the border of other fora -- like ICAO). The charter is also explicitly requesting the re-use of existing protocols as much as possible.


 Understood and stipulated. I'm explicitly second-guessing IETF consensus on this one from the vantage point of hypotheticals such as "If I were looking for standards in this area, where would I first look?", mostly because I have had the discussion of scope creep in the past with fellow IETFers and wanted a concrete example of what I mean by that documented somewhere.

Anyway, I expected to be in the rough on this one, so I won't belabor it further.
Thanks,
Kyle
> 
> >
