### ISSUE TITLE
Robert Wilton: Nit

### ISSUE THREAD

**Issue by ShuaiZhao** [ietf-wg-drip/draft-ietf-drip-arch#46]
Rob: This is somewhat outside my area, and this is a minor comment, but I have to
confess that I found it slightly harder to read, I think because it is fairly
acronym heavy, and I wonder whether expanding out some of the less frequently
used acronyms may end up making the document slightly more readable and
approachable.

**Comment by boucadair** [comment]
Made some few changes but all acronyms seem to be adequately expanded. See https://github.com/ietf-wg-drip/draft-ietf-drip-arch/commit/c2ad8eb9809915edcc3ae345d11097619c09f953
