### ISSUE TITLE
Murray Kucherawy

### ISSUE THREAD

**Issue by ShuaiZhao** [ietf-wg-drip/draft-ietf-drip-arch#47]
Murray:

I'm a little concerned at the shepherd writeup, which claims the bulk of the
review is being done by the co-authors and the chairs.  Where's the rest of the
working group?  And given the content of Section 4.2.2, has anyone from REGEXT
looked at this?

Also, question #8 on the writeup was not answered, although it's possible it
was folded into the answer for #7.  This should be clarified if possible as
it's important to have properly recorded.

I can't parse the second paragraph of Section 3.1.

In Section 3.2, should "trustworthy" be capitalized as it was in the prior
section?  Also in Section 3.2, the sixth paragraph (starting "Ed25519") seems
to be a bit mangled.

The SHOULD in Section 4.1.2 needs expansion.  Why might an implementer
legitimately choose not to do what this says?  Or does this really need to be a
MUST?

**Comment by cardsw** [comment]
I hope that most of these have been addressed in changes between -24 and -29.
In the swc branch, I just briefly addressed the 3rd comment, on the confusing second paragraph of Section 3.1.

**Comment by cardsw** [comment]
Pushed to swc branch on GitHub.
