### ISSUE TITLE
Zaheduzzaman Sarker

### ISSUE THREAD

**Issue by ShuaiZhao** [ietf-wg-drip/draft-ietf-drip-arch#48]
Zahed:
 
Thanks for working on this documentation. Special thanks to Kyle Rose for the
TSVART review. Like Kyle I haven't picked up any TSV related issues. However, I
have some comments which I believe will improve the document if addressed. See
below --

- Section 1.1 : would be great to point to the 3GPP TR or TS for release 17 as
well. An elaboration on how the UAS RID may be used as 3GPP CAA-level UAS RID
would also be helpful here. Was this considered when the DRIP UAS RID designed
so this is a direct match or the  3GPP needs some modification to adopt DRIP
UAS RID.

Overall, I like the idea of describing regulation bodies and other SDOs in this
section. However, due to various level of description and intentions, it feels
this section is not clear about what it want to achieve.

- Section 1.4: Looking at the description it feels like the only reason figure
4 has two UASs is the V2V communication. It became a bit confusing for me to
understand if there is any possibility of GCS in UAS1 sending command to UA in
UAS2 or not. Or whether  GCS in UAS1 and UAS2 is representing same entity
administrated by same  authority/controller. I went through the description
with this confusion in mind and could not resolve it, may be I have missed it
somehow. It will be great if this clarified in the description more vividly.

- Section 3: where is HHIT defined in  RFC 7401? or what is the purpose of
referring to RFC 7401 in the beginning of the section?

- Where is the description of how to self-generate a DRIP Identifier? one
possible answer could be  " Read this in section x of RFC xxx or in this
document or read carefully here []", meaning I have surely missed something.
But then I know where to read and how to generate the DRIP identifier.

**Comment by cardsw** [comment]
I hope that most of these have been addressed in changes between -24 and -29.
In the swc branch, I just briefly addressed the 2nd comment, on V2V etc. in Section 1.4.

**Comment by cardsw** [comment]
Pushed to swc branch on GitHub.
