### ISSUE TITLE
Warren Kumari

### ISSUE THREAD

**Issue by ShuaiZhao** [ietf-wg-drip/draft-ietf-drip-arch#49]
Thank you for writing this; I find "architecture" and "use-case" documents to
be really helpful to understand how things are supposed to work, to get a "lay
of the land", how various components are supposed to fit together, etc -- so,
thank you for writing this.

Roman's security review is, as usual, very thorough -- I did have a few
additional security thoughts / questions which I'm suspecting may already have
been addressed, but which I missed.

1: It seems like a relay attack would be fairly trivial with the broadcast
model -- either just record previous broadcasts from a drone in a similar
position and just replay it, or if there are multiple drones in a similar area
(they often seem to flock together near "interesting" events), simply have a
receiver which records a broadcast and then replays it. The document does say
(Sec 5): "Only sending the DET and a signature on frequently changing data that
can be sanity-checked by the Observer (such as a Location/Vector message)
proves that the observed UA possesses the claimed UAS ID." -- it seems like a
note in the Security Considerations pointing back at this section would be good.

2: Based on how often keys are extracted even from devices which are "supposed"
to be designed for security, I'm fairly sure that there will be trivial attacks
for extracting private keys from small cheap drones and using them in "rogue"
devices - the document does say "Leakage of the private key either from the UA
or GCS to the component manufacturer is a valid concern and steps need to be in
place to ensure safe keeping of the private key." but then "...  it is out of
scope to deal wtih secure store for the private key." -- it feels to me like
this is a fairly serious issue which is being hand-waved away with "it's out of
scope..."

3: Nit: scope to deal wtih secure s/wtih/with/

4: "a revision to [F3411], currently in balloting (as of Oct 2021), adds type
4," -- presumably this has finished balloting - what was the outcome?

**Comment by cardsw** [comment]
I hope that most of these have been addressed in changes between -24 and -29.
In the swc branch, in Security Considerations, I just briefly addressed the comment on replay attacks.

**Comment by cardsw** [comment]
Pushed to swc branch on GitHub.
