### ISSUE TITLE
clarification in Section 1.2.1

### ISSUE THREAD

**Issue by mglt** [ietf-wg-drip/draft-ietf-drip-arch#7]
1.2.1.  Broadcast RID

"""
Internet (or other Wide
   Area Network) connectivity is only needed for UAS registry
   information lookup by Observers using the locally directly received
   UAS RID as a key.  Broadcast RID should be functionally usable in
   situations with no Internet connectivity.
"""

I am wondering why we have "locally received". I have the impression this could be removed. At least, their presence make me thought that maybe there is something I am missing.

**Comment by ShuaiZhao** [comment]
@mglt  that was the original wording by Stu (unfortunately he is not in github). 

We can remove it. "Locally", in my understanding, is the RID received from BRID, which then being used for UAS registry searching.

**Comment by mglt** [comment]
agree. I let you close the issue when implemented.

**Comment by cardsw** [comment]
I am in Github now. That was language I inserted to address confusion. It means what Shuai said above: received via B-RID; then can be used to look things up in registries, if connectivity is available. The point is that obtaining the UAS ID does not depend upon Internet connectivity, only local direct RF broadcast, but that _using_ the UAS ID to look up other information does require some form of WAN connectivity.

**Comment by ShuaiZhao** [comment]
I removed "locally" with the understanding that everyone is on the same page.
Consider this closed. 
`Internet (or other Wide Area Network) connectivity is only needed for UAS registry information lookup by Observers **using the directly received UAS ID**.  Broadcast RID should be functionally usable in situations with no Internet connectivity.`
