### ISSUE TITLE
text clarification 

### ISSUE THREAD

**Issue by mglt** [ietf-wg-drip/draft-ietf-drip-arch#9]
1.2.2.  Network RID
"""
   Command and Control (C2) must flow from the GCS to the UA via some
   path, currently (in the year of 2021) typically a direct RF link, but
   with increasing BVLOS operations expected often to be wireless links
"""
BVLOS  needs to be expanded. It is also unclear to me what the difference is beween RF and wireless link. I tend to see the RF as a wireless link. I have the impression the text wants to mention that in some case, a human will be the C2, while it is foreseen in the future that a sort of base station will be used. 
If that is correct, I believe the base station will only relay C2 from a remote GCS, but will not implement a C2. Am I missing something ?

It seems the text may be clarified.

**Comment by ShuaiZhao** [comment]
> 1.2.2. Network RID
> """
> Command and Control (C2) must flow from the GCS to the UA via some
> path, currently (in the year of 2021) typically a direct RF link, but
> with increasing BVLOS operations expected often to be wireless links
> """
> BVLOS needs to be expanded. 

I will expand BVLOS to "beyond Visual Line of Sight (BVLOS)"

> It is also unclear to me what the difference is beween RF and wireless link. I tend to see the RF as a wireless link.


> I am wondering if read the whole sentence below would help. I think it is saying that RF wireless link needs to be connected with the Internet for C2 to work.   There is no confusion about RF is/not a wireless link

> "Command and Control (C2) must flow from the GCS to the UA via some path, currently (in the year of 2021) typically a direct RF link, but with increasing beyond Visual Line of Sight (BVLOS) operations expected often to be wireless links at either end with the Internet between."

> I have the impression the text wants to mention that in some case, a human will be the C2, while it is foreseen in the future that a sort of base station will be used. If that is correct, I believe the base station will only relay C2 from a remote GCS, but will not implement a C2. Am I missing something ?
> 
> It seems the text may be clarified.

As I explained above, C2 only works with GCS with an internet connection for Network RID.

**Comment by mglt** [comment]
"""but
with increasing BVLOS operations expected often to be wireless links
"""

We need to explain the difference with wireless and RF link clearly. Probably explicitly listing the "either end" would be clarifying also. 

Again, the architecture document should be primarily clarifying for the basic usage - of today. How it might be extended and used in the future is informative - even though we now that has impacted the architecture design.

**Comment by cardsw** [comment]
The remote pilot uses the GCS to exercise essential Command & Control (C2) of the UA via some data path. That may be a direct RF (aka wireless) link. It may be a path through the Internet. In the latter case, both the GCS and the UA have Internet connectivity, so either could use it to send Network RID to the NetRID-SP. In the former case, one end or the other (typically the GCS) would need not only direct C2 link but also Internet connectivity to send Network RID to the NetRID-SP.

**Comment by ShuaiZhao** [comment]
added editor-note 2

```
> Editor-note 2:  Explain the difference with wireless and RF link includes what are the end entities, usages for each transport media.

```

**Comment by ShuaiZhao** [comment]
closed. no more comments from the mailing list.
